import React, { useMemo, CSSProperties, ChangeEvent } from "react";
import Image from "next/image";
import moment from "moment";
import classes from "./ticket-card.module.css";
import { useParams } from "next/navigation";
import { Tooltip } from "@mui/material";
import PaginationComponent from "@/components/global/pagination/pagination";

interface TicketCardBoxProps {
  data: any;
  handleDeleteModal?: (id: number | null) => void;
  inlineStyling?: CSSProperties;
  filters: any;
  updateFilter: (key: string, value: string) => void;
}

const TicketCardBox: React.FC<TicketCardBoxProps> = ({
  data,
  handleDeleteModal,
  inlineStyling,
  filters,
  updateFilter,
}) => {
  const params = useParams();
  const { role } = params;

  const isRowClickable = useMemo(
    () => role === "superAdmin" || role === "admin" || role === "counsellor",
    [role],
  );

  const parseEnrollmentName = useMemo(
    () => (name: string) => {
      const parts = name.split(" | ").map((part) => part.trim());
      const studentAndTutor = parts[0]?.split("/").map((part) => part.trim());
      return {
        studentName: studentAndTutor?.[0] || "N/A",
        tutorName: studentAndTutor?.[1]?.replace(" -", "").trim() || "N/A",
        curriculum: parts[1] || "N/A",
        board: parts[2] || "N/A",
        grade: parts[3] || "N/A",
        subject: parts[4] || "N/A",
      };
    },
    [],
  );

  const getPriorityColor = (priority: string) => {
    switch (priority?.toLowerCase()) {
      case "high":
        return "var(--red-color)";
      case "medium":
        return "var(--orange-color)";
      case "low":
        return "var(--green-color)";
      default:
        return "var(--darkGrey-color)";
    }
  };

  const getStatusColor = (status: string) => {
    switch (status?.toLowerCase()) {
      case "open":
        return "var(--green-color)";
      case "closed":
        return "var(--red-color1)";
      case "in_progress":
        return "var(--orange-color)";
      default:
        return "var(--darkGrey-color)";
    }
  };

  return (
    <div className={classes.contentBox}>
      <div className={classes.cardContainer}>
        {data?.data.map((item: any, index: number) => {
          const enrollmentDetails = item?.enrollment?.name
            ? parseEnrollmentName(item.enrollment.name)
            : null;

          return (
            <div
              key={item.id || index}
              className={classes.container}
              style={{
                cursor: isRowClickable ? "pointer" : "default",
                ...inlineStyling,
              }}
            >
              {/* Header with ID and Date */}
              <div className={classes.header}>
                <span className={classes.id}>Ticket ID: {item.id}</span>
                <span className={classes.id}>
                  Date: &nbsp;
                  {item.createdAt
                    ? moment.utc(item.createdAt).local().format("DD-MMM-YYYY")
                    : "N/A"}
                </span>
              </div>
              {/* Priority and Status */}
              <div className={classes.secondBox}>
                <div className={classes.field}>
                  <span className={classes.label}>Ticket Priority</span>
                  <span
                    className={classes.badge}
                    style={{
                      backgroundColor: getPriorityColor(item.priority),
                      color: "white",
                      width: "max-content",
                    }}
                  >
                    {item.priority.split("_")[0].charAt(0).toUpperCase() +
                      item.priority.split("_")[0].slice(1) || "N/A"}
                  </span>
                </div>
                <div className={classes.field}>
                  <span className={classes.label}>Status</span>
                  <span
                    className={classes.badge}
                    style={{
                      backgroundColor: getStatusColor(item.status),
                      color: "white",
                      width: "max-content",
                    }}
                  >
                    {item.status.split("_")[0].charAt(0).toUpperCase() +
                      item.status.split("_")[0].slice(1) || "N/A"}
                  </span>
                </div>
                {/* Generated By and Recipients */}
                <div className={classes.field}>
                  <span className={classes.label}>Generated By</span>
                  <span className={classes.value}>
                    {item.createdBy?.name || "N/A"}
                  </span>
                </div>
                <div className={classes.field}>
                  <span className={classes.label}>Recipients</span>
                  <span className={classes.value}>
                    {item.recipients && item.recipients.length > 0 ? (
                      <>
                        {item.recipients[0]?.name}
                        {item.recipients.length > 1 && (
                          <span style={{ color: "#2196f3" }}>
                            {" "}
                            +{item.recipients.length - 1} more
                          </span>
                        )}
                      </>
                    ) : (
                      "N/A"
                    )}
                  </span>
                </div>
                {/* Enrollment ID and Priority */}
                <div className={classes.field}>
                  <span className={classes.label}>Enrollment ID</span>
                  <span className={classes.value}>
                    {item.enrollment_id || "N/A"}
                  </span>
                </div>
                <div className={classes.field}>
                  <span className={classes.label}>Enrollment Priority</span>
                  <span
                    className={classes.badge}
                    style={{
                      backgroundColor: getPriorityColor(
                        item.enrollment?.priority,
                      ),
                      color: "white",
                      width: "max-content",
                    }}
                  >
                    {item.enrollment?.priority || "N/A"}
                  </span>
                </div>
                <div className={classes.field}>
                  <span className={classes.label}>Student</span>
                  <span className={classes.value}>
                    {enrollmentDetails?.studentName || "N/A"}
                  </span>
                </div>
                <div className={classes.field}>
                  <span className={classes.label}>Teacher</span>
                  <span className={classes.value}>
                    {enrollmentDetails?.tutorName || "N/A"}
                  </span>
                </div>

                {/* Subject, Grade, Board, Curriculum */}
                <div className={classes.field}>
                  <span className={classes.label}>Subject</span>
                  <span className={classes.value}>
                    {enrollmentDetails?.subject || "N/A"}
                  </span>
                </div>
                <div className={classes.field}>
                  <span className={classes.label}>Grade</span>
                  <span className={classes.value}>
                    {enrollmentDetails?.grade || "N/A"}
                  </span>
                </div>

                <div className={classes.field}>
                  <span className={classes.label}>Board</span>
                  <span className={classes.value}>
                    {enrollmentDetails?.board || "N/A"}
                  </span>
                </div>
                <div className={classes.field}>
                  <span className={classes.label}>Curriculum</span>
                  <span className={classes.value}>
                    {enrollmentDetails?.curriculum || "N/A"}
                  </span>
                </div>

                {/* Actions */}
                <div className={classes.iconsContainer}>
                  <div className={classes.actionsBox}>
                    <Tooltip title={"Delete Ticket"} arrow>
                      <span
                        className={classes.iconBox}
                        onClick={(e) => {
                          e.stopPropagation();
                          if (handleDeleteModal) handleDeleteModal(item.id);
                        }}
                      >
                        <Image
                          src="/assets/svgs/delete.svg"
                          alt="delete"
                          width={0}
                          height={0}
                          style={{
                            width: "var(--regular18-)",
                            height: "var(--regular18-)",
                          }}
                        />
                      </span>
                    </Tooltip>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
      <PaginationComponent
        totalPages={data?.pagination?.totalPages || 0}
        page={data?.pagination?.page || 0}
        rowsPerPage={filters.limit}
        totalEntries={data?.pagination?.total || 0}
        onPageChange={(_event: ChangeEvent<unknown>, newPage: number) => {
          updateFilter("page", String(newPage));
        }}
        rowsPerPageChange={(event: ChangeEvent<HTMLSelectElement>) => {
          updateFilter("limit", String(parseInt(event?.target?.value, 10)));
        }}
        dropDownValues={[50, 100, 200, 300]}
        inlineStyles={{ padding: "5px 0px", width: "100%" }}
      />
    </div>
  );
};

export default TicketCardBox;
