"use client";
import { useState, useCallback, useMemo, ChangeEvent } from "react";
import classes from "./tickets.module.css";
import {
  getAllTickets,
  deleteTicket,
} from "@/services/dashboard/superAdmin/tickets/tickets";
import { useAppSelector } from "@/lib/store/hooks/hooks";
import { useQuery, useMutation } from "@tanstack/react-query";
import LoadingBox from "@/components/global/loading-box/loading-box";
import ErrorBox from "@/components/global/error-box/error-box";
import { MyAxiosError } from "@/services/error.type";
import { toast } from "react-toastify";
import MobileFilterButton from "@/components/global/mobile-filters-button/mobile.filters-button";
import MultiSelectDropDown from "@/components/global/multi-select-dropDown/multi-select-dropDown";
import FilterByDate from "@/components/global/filter-by-date/filter-by-date";
import DeleteModal from "@/components/ui/superAdmin/enrollment/delete-modal/delete-modal";
import SearchBox from "@/components/global/search-box/search-box";
import useDebounce from "@/utils/helpers/useDebounce";
import FilterDropdown from "@/components/global/filter-dropdown/filter-dropdown";
import { useParams } from "next/navigation";
import TicketCardBox from "@/components/ui/superAdmin/tickets/ticket-card/ticket-card";
import CollapsibleTable from "@/components/ui/superAdmin/tickets/collapsible-table/collapsible-table";
import { useMediaQuery } from "react-responsive";

const dropDownStyles = {
  minWidth: "320px",
  background: "var(--main-white-color)",
};

const headData: { id: number; name: string; width: string }[] = [
  { id: 0, name: "", width: "4%" },
  { id: 1, name: "Date", width: "10%" },
  { id: 2, name: "Ticket Priority", width: "10%" },
  { id: 3, name: "Status", width: "7%" },
  { id: 4, name: "Generated By", width: "15%" },
  { id: 5, name: "Recipients", width: "12%" },
  { id: 6, name: "Enroll ID", width: "8%" },
  { id: 6, name: "Enroll Priority", width: "10%" },
  { id: 7, name: "Student", width: "12%" },
  { id: 8, name: "Teacher", width: "12%" },
];

export type FilterState = {
  dateFilter: string | [string, string] | null;
  selectedTeacher: string;
  selectedStudent: string;
  on_break: boolean | undefined;
  subjectId: string[];
  boardId: string[];
  gradeId: string[];
  curriculumId: string[];
  page: number;
  limit: number;
  enrollment_ids: string;
  priority: string;
  generatedByRoleIds: string[];
  teacher_ids: string[];
  student_ids: string[];
};

const initialFilterState: FilterState = {
  dateFilter: "",
  selectedTeacher: "",
  selectedStudent: "",
  subjectId: [],
  boardId: [],
  gradeId: [],
  curriculumId: [],
  page: 1,
  limit: 50,
  enrollment_ids: "",
  priority: "",
  generatedByRoleIds: [],
  teacher_ids: [],
  student_ids: [],
  on_break: undefined,
};

const Tickets = () => {
  const mobileViewport = useMediaQuery({ maxWidth: 1199 });
  const { role } = useParams();
  const isAdminRole =
    role === "superAdmin" ||
    role === "admin" ||
    role === "counsellor" ||
    role === "hr";
  const { token, user } = useAppSelector((state) => state.user);
  const { roles } = useAppSelector((state) => state.roles);
  const { students, teachers } = useAppSelector((state) => state?.usersByGroup);
  const { subject, curriculum, board, grades } = useAppSelector(
    (state) => state.resources,
  );
  const [showFullFilters, setShowFullFilters] = useState<boolean>(false);
  const [filters, setFilters] = useState<FilterState>(initialFilterState);
  const debouncedSearch = useDebounce(filters.enrollment_ids, 1500);
  const [deleteModal, setDeleteModal] = useState<{
    open: boolean;
    deleteId: number | null;
  }>({
    open: false,
    deleteId: null,
  });

  const handleMobileFilterToggle = useCallback(() => {
    setShowFullFilters((prev) => !prev);
  }, []);

  const updateFilter = useCallback((key: string, value: any) => {
    setFilters((prev) => ({
      ...prev,
      [key]: value,
      ...(key !== "page" && key !== "limit" ? { page: 1 } : {}),
    }));
  }, []);

  const handleStudentFilter = useCallback(
    (e: React.SyntheticEvent, selectedOptions: { id: number }[]) => {
      const selectedIds = selectedOptions.map((option) => String(option.id));
      updateFilter("student_ids", selectedIds);
    },
    [updateFilter],
  );

  const handleTeacherFilter = useCallback(
    (e: React.SyntheticEvent, selectedOptions: { id: number }[]) => {
      const selectedIds = selectedOptions.map((option) => String(option.id));
      updateFilter("teacher_ids", selectedIds);
    },
    [updateFilter],
  );

  const { data, isLoading, error, refetch } = useQuery({
    queryKey: [
      "getAllTickets",
      filters.dateFilter,
      filters.curriculumId,
      filters.gradeId,
      filters.subjectId,
      filters.boardId,
      filters.limit,
      filters.page,
      filters.priority,
      filters.generatedByRoleIds,
      filters.student_ids,
      filters.teacher_ids,
      filters.on_break,
      debouncedSearch,
    ],
    queryFn: () =>
      getAllTickets(
        {
          startDate: Array.isArray(filters?.dateFilter)
            ? filters.dateFilter[0]
            : undefined,
          endDate: Array.isArray(filters?.dateFilter)
            ? filters.dateFilter[1]
            : undefined,
          curriculumId: filters?.curriculumId.join(","),
          gradeId: filters?.gradeId.join(","),
          subjectId: filters?.subjectId.join(","),
          boardId: filters?.boardId.join(","),
          limit: filters?.limit,
          page: filters?.page,
          enrollment_ids: debouncedSearch,
          priority: filters?.priority,
          on_break:
            filters?.on_break !== undefined
              ? Boolean(filters?.on_break)
              : undefined,
          generatedByRoleIds:
            (role === "superAdmin" || role === "admin") &&
            filters?.generatedByRoleIds.length > 0
              ? filters?.generatedByRoleIds.join(",")
              : undefined,
          student_ids:
            role === "student"
              ? String(user?.id)
              : filters?.student_ids.length > 0
                ? filters?.student_ids.join(",")
                : undefined,
          teacher_ids:
            role === "teacher"
              ? String(user?.id)
              : filters?.teacher_ids.length > 0
                ? filters?.teacher_ids.join(",")
                : undefined,
        },
        { token },
      ),
    refetchOnWindowFocus: false,
    refetchInterval: 60000,
    staleTime: 60000,
  });

  const handleDeleteTicket = useMutation({
    mutationFn: (deleteId: number | null) => {
      if (!deleteId) {
        return Promise.reject(new Error("Invalid ticket ID"));
      }
      return deleteTicket(deleteId, { token });
    },
    onSuccess: (data: any) => {
      ["message", "error"].forEach((type) => {
        if (data[type]) {
          toast[type === "message" ? "success" : "error"](data[type]);
        }
      });
      refetch();
      setDeleteModal({ open: false, deleteId: null });
    },
    onError: (error) => {
      const axiosError = error as MyAxiosError;
      toast.error(
        axiosError.response
          ? axiosError.response.data.error ||
              `${axiosError.response.status} ${axiosError.response.statusText}`
          : axiosError.message,
      );
      setDeleteModal({ open: false, deleteId: null });
    },
  });

  const mobileFilterButtonProps = useMemo(
    () => ({
      isOpen: showFullFilters,
      onClick: handleMobileFilterToggle,
      inlineStyles: { alignSelf: "flex-end" },
    }),
    [showFullFilters, handleMobileFilterToggle],
  );

  const filterByDateProps = useMemo(
    () => ({
      changeFn: (value: [string, string] | null) => {
        updateFilter("dateFilter", value === null ? "" : value);
      },
      value: filters.dateFilter,
      minWidth: "250px",
      flex: 1,
    }),
    [filters.dateFilter, updateFilter],
  );

  const studentFilterProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Student",
      handleChange: handleStudentFilter,
      data: students?.users || [],
      value:
        students?.users?.filter((student) =>
          filters.student_ids.includes(String(student.id)),
        ) || [],
    }),
    [handleStudentFilter, students?.users, filters.student_ids],
  );

  const teacherFilterProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Teacher",
      data: teachers?.users || [],
      value:
        teachers?.users?.filter((teacher) =>
          filters.teacher_ids.includes(String(teacher.id)),
        ) || [],
      handleChange: handleTeacherFilter,
    }),
    [handleTeacherFilter, teachers?.users, filters.teacher_ids],
  );

  const searchBoxProps = useMemo(
    () => ({
      placeholder: "Search By Enroll_ID",
      changeFn: (event: ChangeEvent<HTMLInputElement>) => {
        updateFilter("enrollment_ids", event.target.value);
      },
      value: filters.enrollment_ids ? String(filters.enrollment_ids) : "",
      inlineStyles: {
        ...dropDownStyles,
      },
    }),
    [filters.enrollment_ids, updateFilter],
  );

  const priorityFilterProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Priority",
      data: ["Low", "Medium", "High"],
      handleChange: (value: string) => {
        updateFilter("priority", value);
      },
      value: filters.priority,
    }),
    [filters.priority, updateFilter],
  );

  const multiSelectGeneratedByRoleProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Generated By Role",
      data: roles || [],
      handleChange: (
        e: React.SyntheticEvent,
        selectedOptions: { id: number }[],
      ) => {
        const selectedIds = selectedOptions.map((option) => String(option.id));
        updateFilter("generatedByRoleIds", selectedIds);
      },
      value:
        roles?.filter((roleItem) =>
          filters.generatedByRoleIds.includes(String(roleItem?.id)),
        ) || [],
    }),
    [roles, filters.generatedByRoleIds, updateFilter],
  );

  const filterByStatusProps = useMemo(
    () => ({
      placeholder: "Filter By Status",
      data: ["paused", "unpaused"],
      handleChange: (value: string) => {
        updateFilter("on_break", Boolean(value));
      },
      value: filters?.on_break === undefined ? "" : String(filters?.on_break),
      inlineBoxStyles: dropDownStyles,
    }),
    [filters.on_break, updateFilter],
  );

  const multiSelectSubjectProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Subject",
      data: subject || [],
      handleChange: (
        e: React.SyntheticEvent,
        selectedOptions: { id: number }[],
      ) => {
        const selectedIds = selectedOptions.map((option) => String(option.id));
        updateFilter("subjectId", selectedIds);
      },
      value:
        subject?.filter((subjectItem) =>
          filters.subjectId.includes(String(subjectItem?.id)),
        ) || [],
    }),
    [subject, filters.subjectId, updateFilter],
  );

  const multiSelectBoardProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Board",
      data: board || [],
      handleChange: (
        e: React.SyntheticEvent,
        selectedOptions: { id: number }[],
      ) => {
        const selectedIds = selectedOptions.map((option) => String(option.id));
        updateFilter("boardId", selectedIds);
      },
      value:
        board?.filter((boardItem) =>
          filters.boardId.includes(String(boardItem?.id)),
        ) || [],
    }),
    [board, filters.boardId, updateFilter],
  );

  const multiSelectGradeProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Grade",
      data: grades || [],
      handleChange: (
        e: React.SyntheticEvent,
        selectedOptions: { id: number }[],
      ) => {
        const selectedIds = selectedOptions.map((option) => String(option.id));
        updateFilter("gradeId", selectedIds);
      },
      value:
        grades?.filter((gradeItem) =>
          filters.gradeId.includes(String(gradeItem?.id)),
        ) || [],
    }),
    [grades, filters.gradeId, updateFilter],
  );

  const multiSelectCurriculumProps = useMemo(
    () => ({
      icon: true,
      inlineBoxStyles: {
        ...dropDownStyles,
      },
      placeholder: "Filter Curriculum",
      data: curriculum || [],
      handleChange: (
        e: React.SyntheticEvent,
        selectedOptions: { id: number }[],
      ) => {
        const selectedIds = selectedOptions.map((option) => String(option.id));
        updateFilter("curriculumId", selectedIds);
      },
      value:
        curriculum?.filter((curriculumItem) =>
          filters.curriculumId.includes(String(curriculumItem?.id)),
        ) || [],
    }),
    [curriculum, filters.curriculumId, updateFilter],
  );

  const deleteModalProps = useMemo(
    () => ({
      modalOpen: deleteModal.open,
      handleClose: () => setDeleteModal({ open: false, deleteId: null }),
      subHeading:
        "Are you sure you want to delete this ticket? This action is permanent.",
      heading: "Are You Sure?",
      handleDelete: () => handleDeleteTicket.mutate(deleteModal?.deleteId),
      loading: handleDeleteTicket?.isPending,
    }),
    [deleteModal.open, deleteModal.deleteId, handleDeleteTicket],
  );

  if (error) {
    const axiosError = error as MyAxiosError;
    if (axiosError.response) {
      toast.error(axiosError.response.data.error);
    } else {
      toast.error(axiosError.message);
    }
  }

  return (
    <div className={classes.container}>
      <MobileFilterButton {...mobileFilterButtonProps} />
      {showFullFilters && (
        <div className={classes.filtersBox}>
          <FilterByDate {...filterByDateProps} />
          {role !== "student" && (
            <MultiSelectDropDown {...studentFilterProps} />
          )}
          {role !== "teacher" && (
            <MultiSelectDropDown {...teacherFilterProps} />
          )}
          <SearchBox {...searchBoxProps} />
          <FilterDropdown {...priorityFilterProps} />
          {isAdminRole && (
            <>
              <MultiSelectDropDown {...multiSelectGeneratedByRoleProps} />
              <FilterDropdown {...filterByStatusProps} />
            </>
          )}
          <MultiSelectDropDown {...multiSelectSubjectProps} />
          <MultiSelectDropDown {...multiSelectBoardProps} />
          <MultiSelectDropDown {...multiSelectGradeProps} />
          <MultiSelectDropDown {...multiSelectCurriculumProps} />
        </div>
      )}

      {isLoading && <LoadingBox inlineStyling={{ flex: 1 }} />}

      {error ||
      (data && Array.isArray(data?.data) && data?.data?.length <= 0) ? (
        <ErrorBox inlineStyling={{ flex: 1 }} />
      ) : (
        data &&
        Array.isArray(data?.data) &&
        data?.data?.length > 0 &&
        (!mobileViewport ? (
          <CollapsibleTable
            data={data?.data}
            headData={headData}
            totalPages={data?.pagination?.totalPages || 0}
            page={data?.pagination?.page || 0}
            rowsPerPage={filters.limit}
            totalEntries={data?.pagination?.total || 0}
            onPageChange={(_event: ChangeEvent<unknown>, newPage: number) => {
              updateFilter("page", newPage);
            }}
            rowsPerPageChange={(event: ChangeEvent<HTMLSelectElement>) => {
              updateFilter("limit", parseInt(event?.target?.value, 10));
            }}
            handleDeleteModal={(id: number | null) => {
              setDeleteModal({ open: true, deleteId: id });
            }}
          />
        ) : (
          <TicketCardBox
            data={data}
            handleDeleteModal={(id: number | null) => {
              setDeleteModal({ open: true, deleteId: id });
            }}
            filters={filters}
            updateFilter={updateFilter}
          />
        ))
      )}

      <DeleteModal {...deleteModalProps} />
    </div>
  );
};

export default Tickets;
